Repository abhijeetnishal/URLShortener, pull requests merged in 2024-05, with the labels that each got.

#14 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#13 Add Learn.md
  Learn.md
Labels: documentation

#12 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#25 Refactored MongoDB connection to only initiate when required
  server/controller/urlController.js
  server/model/dbConnect.js
  server/server.js
Labels: refactor

#30 Restructure react project into next app
  client/.env.sample
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/next.config.mjs
  client/package-lock.json
  client/package.json
  client/postcss.config.mjs
  client/public/chain.png
  client/public/copy.png
  client/public/http.png
  client/public/index.html
  client/public/manifest.json
  client/public/next.svg
  client/public/vercel.svg
  client/src/App.js
  client/src/Styles/homeScreen.css
  client/src/Styles/loading.css
  client/src/app/favicon.ico
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/components/HomeScreen.jsx
  client/src/components/Loading.jsx
  client/src/components/Navbar.tsx
  client/src/index.css
  client/src/index.js
  client/tailwind.config.ts
  client/tsconfig.json
  server/.env.example
  server/controller/urlController.js
  server/model/dbConnect.js
  server/server.js
Labels: refactor

#69 Feat: Automate greeting using Github bot 🤖
  .github/workflows/greetings,yml
Labels: gssoc, level1

#77 Favicon logo added inn the header of the website
  client/src/app/favicon.ico
  client/src/app/layout.tsx
Labels: good first issue, gssoc

#85 [FEAT]:Add RateLimit using Redis
  Setup.sh
  client/package-lock.json
  client/package.json
  client/src/app/page.tsx
  server/.env.example
  server/config/redis.js
  server/controller/rateLimit.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/routes/url.js
Labels: gssoc, level2

#94 Fixed #44 Made Ui responsive for all devices
  client/src/app/page.tsx
  client/src/components/Navbar.tsx
Labels: good first issue, gssoc, level1

#111 share shorten url to whatsapp, gmail, linkedin without copying it
  client/client/.env.sample
  client/client/.eslintrc.json
  client/client/.gitignore
  client/client/next.config.mjs
  client/client/package-lock.json
  client/client/package.json
  client/client/postcss.config.mjs
  client/client/public/chain.png
  client/client/public/copy.png
  client/client/public/copyi.svg
  client/client/public/http.png
  client/client/public/next.svg
  client/client/public/vercel.svg
  client/client/src/app/favicon.ico
  client/client/src/app/globals.css
  client/client/src/app/layout.tsx
  client/client/src/app/page.tsx
  client/client/src/components/Navbar.tsx
  client/client/tailwind.config.ts
  client/client/tsconfig.json
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/icons/GmailIcon.tsx
  client/src/icons/LinkedInIcon.tsx
  client/src/icons/WhatsAppIcon.tsx
  server/config/mixpanel.js
  server/model/urlSchema.js
Labels: gssoc, level1

#108 Toggle Button for Light/Dark added
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/app/globals.css
  client/src/app/page.tsx
  client/src/components/Navbar.tsx
  client/src/components/ThemeToggle.tsx
  package-lock.json
  package.json
Labels: gssoc, level1

#110 Added 404 page and backend logic
  client/src/app/404/page.tsx
  client/src/components/Navbar.tsx
  client/src/icons/Page404Icon.tsx
  server/controller/urls.js
Labels: gssoc, level1

#88 middleware added for validating the url
  client/src/app/page.tsx
  server/controller/urls.js
  server/middlewares/url.js
  server/routes/url.js
  server/server.js
Labels: gssoc, level1

#138 solved ThemeToggle issue
  client/src/components/ThemeToggle.tsx
Labels: gssoc, level1
